{{ if .Values.relaxPsp}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:privileged:{{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
{{ end }}


