---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.roleName }}
  namespace: {{ include "userNamespace" . }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - persistentvolumeclaims
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups: [""]
    resources: [ "pods/log" ]
    verbs: [ "get", "list" ]
  - apiGroups: [""]
    resources: [ "pods/portforward" ]
    verbs: [ "get", "list", "create" ]
{{ if .Values.kubernetesJobs.manage }}
  - apiGroups: [ "batch"]
    resources: ["jobs", "cronjobs"]
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
{{ end }}
{{ if .Values.workflow.manage }}
  - apiGroups: [ "argoproj.io" ]
    resources: ["clusterworkflowtemplates", "cronworkflows", "workfloweventbindings", "workflows", "workflowtasksets", "workflowtemplates", "workflowtaskresults" ]
    verbs: ["*"]
{{ end }}
{{ if .Values.secretStore.manage}}
  - apiGroups: [ "external-secrets.io" ]
    resources: [ "secretstores", "externalsecrets" ]
    verbs: ["*"]
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleName }}-{{ .Values.serviceAccountName }}
  namespace: {{ include "userNamespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ include "userNamespace" . }}
roleRef:
  kind: Role
  name: {{ .Values.roleName }}
  apiGroup: rbac.authorization.k8s.io
