{{- if (and .Values.s3access.secretKey .Values.s3access.accessKey) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: s3access
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  accessKey: {{ .Values.s3access.accessKey | b64enc }}
  secretKey: {{ .Values.s3access.secretKey | b64enc }}
{{- end }}