
baseNamespace: # TBD


serviceAccountName: spark
roleName: spark

# Allow service account to manage Kubernetes jobs and cronjobs
kubernetesJobs:
  manage: true

s3access:
  accessKey:
  secretKey:

# Allow service account to manage external-secret secretstore and externalsecrets
secretStore:
  manage: true

workflow:
  manage: false  # True to allow 'service' serviceAccount to manage Argo Workflow resources
  guiOidcGroups: []  # List of OIDC groups which will be impersonated in 'service' account on the Argo workflow server.
